apiVersion: image.openshift.io/v1
kind: ImageStream
metadata:
  name: cuda-jupyter-tensorflow
  namespace: redhat-ods-applications
  labels:
    opendatahub.io/notebook-image: "true"
  annotations:
    opendatahub.io/notebook-image-url: >-
      https://github.com/nerc-images/cuda-jupyter-tensorflow
    opendatahub.io/notebook-image-name: >-
      Tensorflow Jupyter CUDA
    opendatahub.io/notebook-image-desc: >-
      A Jupyter OpenShift AI Image with Tensorflow and CUDA for GPUs.
      Based on the [opendatahub workbench images](https://github.com/opendatahub-io-contrib/workbench-images)
      on GitHub for Jupyter Lab Notebook integration.
spec:
  lookupPolicy:
    local: true
  tags:
    - name: latest
      annotations: null
      from:
        kind: DockerImage
        name: 'quay.io/nerc-images/cuda-jupyter-tensorflow:1.0.0'
      importPolicy:
        scheduled: true
      referencePolicy:
        type: Source
