apiVersion: image.openshift.io/v1
kind: ImageStream
metadata:
  name: jupyter-rust
  namespace: redhat-ods-applications
  labels:
    opendatahub.io/notebook-image: "true"
  annotations:
    opendatahub.io/notebook-image-url: >-
      https://github.com/nerc-images/jupyter-rust
    opendatahub.io/notebook-image-name: >-
      Jupyter Rust
    opendatahub.io/notebook-image-desc: |-
      An OpenShift AI Image running Jupyter Lab for Rust development.
      - Based on the [Evcxr project](https://github.com/evcxr/evcxr)
      on GitHub for Jupyter Lab Notebook integration.
      - Uses Rust 1.79.
      - Used by Professor Leonidas Kontothanassis, MassMutual Professor of the
      Practice of Computing & Data Sciences + Director of Industry Engagement.
spec:
  lookupPolicy:
    local: true
  tags:
    - name: 1.0.0
      annotations: null
      from:
        kind: DockerImage
        name: 'quay.io/nerc-images/jupyter-rust:1.0.0'
      importPolicy:
        scheduled: true
      referencePolicy:
        type: Source
